#!/usr/bin/env bash
SMAC_MEMORY_INPUT=$SMAC_MEMORY
SMACMEM=128
test "$SMAC_MEMORY_INPUT" -ge 1 2>&- && SMACMEM=$SMAC_MEMORY_INPUT
EXEC=ca.ubc.cs.beta.aclib.example.tae.TargetAlgorithmEvaluatorRunner
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Starting algo-test with $SMACMEM MB of RAM"

for f in $DIR/*.jar
do
	jarconcat=$jarconcat:$f
done
jarconcat=${jarconcat:1}

exec java -Xmx"$SMACMEM"m -cp "$DIR/conf/:$DIR/patches/:$jarconcat:$DIR/patches/" $EXEC "$@"
